services:
  postgres:
    image: postgres:latest
    container_name: postgres_dev
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      # CAMBIO AQUÍ: Se quita el "/data" al final de la ruta del contenedor
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: