spring.application.name=api
spring.datasource.url =jdbc:postgresql://localhost:5432/service_01
spring.datasource.username =postgres
spring.datasource.password =root
spring.datasource.driver-class-name =org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto =update
spring.jpa.sql-show =true
spring.jpa.properties.hibernate.format_sql = true
spring.data.redis.host=localhost
spring.data.redis.port=6379
key.security = oo26Ahf99z5FUfd2w14ojKxGW5MBBPTFaxCNsrs0JAFHijleF2EmZjFIh2ACPJnj/Z75UVFilw2kNB6c+UD6qw==
reniec.api.url = https://api.decolecta.com
reniec.api.key = sk_2766.FGMkzxtWmJtaqBFeawMGDc5RHlcKarPK
